project:
  type: website
  output-dir: docs

website:
  title: "Cao Xuân Lộc"
  navbar:
    left:
      - href: index.qmd
        text: "<i class='fa-solid fa-house'></i> Home"
      - href: GA.qmd
        text: "<i class='fa-solid fa-dna'></i> Genetic Algorithm"
      - href: MILP.qmd
        text: "<i class='fa-solid fa-calculator'></i> MILP model"
    right:
      - text: "<i class='fab fa-github'></i>"
        href: https://github.com/Loccx78vn/genetic-algorithm-method

      - text: "<i class='fab fa-facebook'></i>"
        href: https://www.facebook.com/cao.loc.9693

      - text: "<img src='https://www.r-project.org/Rlogo.png' width='20' style='margin-right:5px;'>"
        href: https://rpubs.com/loccx
  page-footer:
    right: "<i class='fa-solid fa-book'></i> Built with [Quarto](https://quarto.org/)"
    left: "© Copyright 2025, [Loc cao](https://github.com/Loccx78vn) <i class='fa-solid fa-heart'></i>"

format:
  html:
    theme: theme.scss 
    grid:
      sidebar-width: 300px    
      body-width: 900px       
      margin-width: 400px    
    toc: true
    include-in-header: 
      - toc-filter.html
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">